name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - run: "echo ${{ env.DATABASE_URL }} for environment: ${{ inputs.environment }}"

  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"