name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - run: "echo ${{ env.DATABASE_URL }} for environment: ${{ inputs.environment }}"

  done:
    runs-on: ubuntu-latest
    needs: [echo]
    steps:
      - run: echo "### Hello world from ${{ inputs.environment }}! :rocket:" >> $GITHUB_STEP_SUMMARY